-- ====================
-- Date Exploration
-- ====================

-- Find the date of the first and last order
-- How many years of sales are avaiable?

SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) As last_order_date,
	DATEDIFF(YEAR,MIN(order_date), MAX(order_date)) sale_years
FROM gold.fact_sales

-- Find the Youngest and the oldest customer
SELECT
	MIN(birthdate) AS oldest_birthdate,
	DATEDIFF(YEAR, MIN(birthdate), GETDATE()) AS oldest_age,
	MAX(birthdate) AS  youngest_birthdate,
	DATEDIFF(YEAR, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers
--==============================
-- Measure Exploration
-- =============================
-- ========================
-- Measures Exploration
-- ========================
-- Find the Total sales
-- Find how many items are sold 
-- Find the average selling price
-- Find the total number of orders
-- Find the total number of products
-- Find the total number of customers
-- Find the total number of customers that have placed an order

SELECT 
	SUM(f.sales_amount) AS total_sales,
	COUNT(f.sales_amount) AS items_sold,
	AVG(f.price) AS avg_selling_price,
	COUNT(DISTINCT f.order_number) AS total_orders,
	COUNT(DISTINCT p.product_key) AS total_products,
	COUNT(DISTINCT c.customer_key) AS total_customers,
	COUNT(DISTINCT c.customer_key) AS customer_order
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key

-- Generate a report that shows all key metrics for the business

SELECT 'Total Sales' AS 'measure_name', SUM(sales_amount) AS 'measure_value' FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products', COUNT(DISTINCT product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers', COUNT(DISTINCT customer_key) FROM gold.fact_sales

-- ==========================
-- Magnitude Analysis
-- =========================
-- Find total customers by countries
SELECT 
	country,
	COUNT(customer_key) total_customers_cntry
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC

-- Find total customers by gender
SELECT 
	gender,
	COUNT(customer_key) total_customers_gen
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers_gen DESC

-- Find total products by category
SELECT 
	category,
	COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category?
SELECT
	category,
	AVG(cost) avg_cost
SELECT *FROM gold.dim_products 
GROUP BY category
ORDER BY avg_cost DESC

-- What is the total revenue generated for each category?
SELECT 
	p.category,
	SUM(s.sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
GROUP BY category
ORDER BY total_revenue DESC

-- Find total revenue is generated by each customer
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT
	c.country,
	SUM(s.quantity) total_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY 
	c.country
ORDER BY total_items DESC

-- ==========================
-- Ranking Analysis
-- =========================
-- Which 5 products generate the highest revenue
SELECT TOP 5
	product_name,
	SUM(sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY product_name
ORDER BY total_revenue DESC

-- What are the 5 worst-performing products in terms of sales?

SELECT  TOP 5
	product_name,
	SUM(sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY product_name
ORDER BY total_revenue 



